---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8084
      targetPort: 8084


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: nikitayatsko/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/payment_db"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: SPRING_EXTERNAL_KAFKA_SERVER
              value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 80
            periodSeconds: 10
            timeoutSeconds: 2

          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
